_target_: pytorch_lightning.Trainer

#gpus: 1
accelerator: "gpu"
devices: "auto"

min_epochs: 1
max_epochs: 1

gradient_clip_val: 1.0


# number of validation steps to execute at the beginning of the training
num_sanity_val_steps: 0