# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8
      - run:
          name: "run linter and tests"
          command: |
            . venv/bin/activate
            flake8 --max-line-length 120
            flake8 --exclude=venv* --statistics
# pytest -v --cov=test