# Python CircleCI 2.1 configuration file
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: "install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            pip install flake8
            ls .
      - run:
          name: "run linter and tests"
          command: |
            . venv/bin/activate
            flake8 . --max-line-length 120 --exclude ./venv
# pytest -v --cov=test