model:
  loss_function: climax_lon_lat_rmse
  monitor: val/llrmse_climax
  optimizer:
    name: adamw
    lr: 0.0005
    weight_decay: 1.0e-05
  _target_: emulator.src.core.models.climax.climax_module.ClimaX
  lon: 96
  lat: 144
  in_vars:
  - BC_sum
  - CO2_sum
  - SO2_sum
  - CH4_sum
  out_vars:
  - tas
  - pr
  climate_modeling: true
  patch_size: 16
  drop_path: 0.1
  drop_rate: 0.1
  learn_pos_emb: false
  channel_agg: attention
  embed_dim: 1024
  depth: 8
  decoder_depth: 2
  num_heads: 16
  mlp_ratio: 4
  init_mode: small
  freeze_encoder: false
  pretrained_path: /home/mila/v/venkatesh.ramesh/scratch/causalpaca/emulator/src/core/models/climax/pretrained_checkpoints/ClimaX-5.625deg.ckpt
  no_time_aggregation: true
  scheduler:
    _target_: emulator.src.utils.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 5
    max_epochs: 50
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-08
  finetune: false
  pretrained_run_id: null
  pretrained_ckpt_dir: null
datamodule:
  batch_size: 4
  _target_: emulator.src.datamodules.climate_datamodule.ClimateDataModule
  in_var_ids:
  - BC_sum
  - CO2_sum
  - SO2_sum
  - CH4_sum
  out_var_ids:
  - tas
  - pr
  seq_to_seq: true
  channels_last: false
  eval_batch_size: 4
  train_historical_years: 1850-2010
  test_years: 2015-2100
  train_years: 2015-2100
  val_split: 0.1
  train_scenarios:
  - ssp126
  - ssp370
  - ssp585
  test_scenarios:
  - ssp245
  train_models:
  - NorESM2-MM
  num_ensembles: 1
  num_workers: 0
  pin_memory: false
  load_train_into_mem: true
  load_test_into_mem: true
  verbose: true
  seed: 11
  output_save_dir: /home/mila/v/venkatesh.ramesh/scratch/causal_savedata
  seq_len: 12
  lon: 96
  lat: 144
  num_levels: 1
work_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator
ckpt_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/checkpoints/
log_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/logs/
print_config: true
ignore_warnings: true
test_after_training: true
save_config_to_wandb: true
verbose: true
seed: 3423
name: NorESM2-MM_climax_tas_run-01
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: auto
  min_epochs: 1
  max_epochs: 50
  gradient_clip_val: 1.0
  num_sanity_val_steps: 0
callbacks: {}
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: NorESM2-MM_climax_tas_run-01ClimaX_adamw_4bs_0.0005lr_1e-05wd_3423seed_03h59m_on_Jun_10_bacfkhjx
    tags:
    - single_emulator
    - climax
    - NorESM2-MM
    - tas+pr
    - run1
    notes: '...'
    project: emulator
    group: causalpaca
    resume: allow
    reinit: true
    mode: online
    save_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/
    offline: false
    id: bacfkhjx
    log_model: false
    prefix: ''
    job_type: train
experiment_mode: true
local: {}
