model:
  loss_function: climax_lon_lat_rmse
  monitor: val/llrmse_climax
  super_emulation: true
  super_decoder: false
  optimizer:
    name: adamw
    lr: 0.0005
    is_filtered: true
    weight_decay: 1.0e-05
  _target_: emulator.src.core.models.climax.climax_module.ClimaX
  lon: 96
  lat: 144
  in_vars:
  - BC_sum
  - SO2_sum
  - CO2_sum
  - CH4_sum
  out_vars:
  - pr
  - tas
  patch_size: 16
  drop_path: 0.1
  drop_rate: 0.1
  learn_pos_emb: false
  channel_agg: attention
  embed_dim: 1024
  depth: 8
  decoder_depth: 2
  num_heads: 16
  mlp_ratio: 4
  init_mode: small
  freeze_encoder: false
  channels_last: true
  pretrained_path: /home/mila/v/venkatesh.ramesh/scratch/causalpaca/emulator/src/core/models/climax/pretrained_checkpoints/ClimaX-5.625deg.ckpt
  no_time_aggregation: true
  scheduler:
    _target_: emulator.src.utils.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 5
    max_epochs: 50
    warmup_start_lr: 1.0e-08
    eta_min: 1.0e-08
  finetune: false
  pretrained_run_id: bcvgpg4b
  pretrained_ckpt_dir: /network/scratch/c/charlotte.lange/causalpaca/emulator/emulator/bcvgpg4b/checkpoints/epoch=8-step=180.ckpt
  pretrained_run_id_decoder: xog84o5g
  pretrained_ckpt_dir_decoder: /network/scratch/c/charlotte.lange/causalpaca/emulator/emulator/xog84o5g/checkpoints/epoch=8-step=180.ckpt
datamodule:
  batch_size: 2
  _target_: emulator.src.datamodules.super_climate_datamodule.SuperClimateDataModule
  in_var_ids:
  - BC_sum
  - SO2_sum
  - CO2_sum
  - CH4_sum
  out_var_ids:
  - pr
  - tas
  seq_to_seq: true
  channels_last: true
  eval_batch_size: 2
  train_historical_years: 1950-1955
  test_years: 2015-2100
  train_years: 2015-2020
  val_split: 0.1
  train_scenarios:
  - ssp126
  - ssp370
  - ssp585
  test_scenarios:
  - ssp245
  train_models:
  - MPI-ESM1-2-HR
  - AWI-CM-1-1-MR
  - NorESM2-LM
  - FGOALS-f3-L
  - EC-Earth3
  - BCC-CSM2-MR
  test_models:
  - MPI-ESM1-2-HR
  - AWI-CM-1-1-MR
  - NorESM2-LM
  - FGOALS-f3-L
  - EC-Earth3
  - BCC-CSM2-MR
  num_ensembles: 1
  num_workers: 0
  pin_memory: false
  load_train_into_mem: true
  load_test_into_mem: true
  verbose: true
  seed: 11
  output_save_dir: /home/mila/v/venkatesh.ramesh/scratch/causalpaca/emulator/DATA
  seq_len: 12
  lon: 96
  lat: 144
  num_levels: 1
  name: climate_super
work_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator
ckpt_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/checkpoints/
log_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/logs/
print_config: true
ignore_warnings: true
test_after_training: true
save_config_to_wandb: true
verbose: true
seed: 99
name: superemulator
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: auto
  min_epochs: 1
  max_epochs: 50
  gradient_clip_val: 5
  num_sanity_val_steps: 0
decoder:
  _target_: emulator.src.core.models.multihead_decoder.MultiHeadDecoder
  in_var_ids:
  - BC_sum
  - SO2_sum
  - CO2_sum
  - CH4_sum
  out_var_ids:
  - pr
  - tas
  train_models:
  - MPI-ESM1-2-HR
  - AWI-CM-1-1-MR
  - NorESM2-LM
  - FGOALS-f3-L
  - EC-Earth3
  - BCC-CSM2-MR
  test_models:
  - MPI-ESM1-2-HR
  - AWI-CM-1-1-MR
  - NorESM2-LM
  - FGOALS-f3-L
  - EC-Earth3
  - BCC-CSM2-MR
  n_layers: 2
  hidden_dim: 32
callbacks: {}
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: superemulatorClimaX_adamw_2bs_0.0005lr_1e-05wd_99seed_12h26m_on_Aug_23_mhd8xjbn
    tags:
    - climax
    - super_emulation
    - decoder
    - 6_models
    notes: '...'
    project: emulator
    group: causalpaca
    resume: allow
    reinit: true
    mode: online
    save_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/
    offline: false
    id: mhd8xjbn
    log_model: false
    prefix: ''
    job_type: train
experiment_mode: true
local: {}
