model:
  loss_function: climax_lon_lat_rmse
  monitor: val/llrmse_climax
  optimizer:
    name: adam
    lr: 0.0002
    weight_decay: 1.0e-06
    eps: 1.0e-08
  _target_: emulator.src.core.models.baselines.UNet
  in_var_ids:
  - BC_sum
  - CO2_sum
  - SO2_sum
  - CH4_sum
  out_var_ids:
  - tas
  - pr
  seq_to_seq: true
  seq_len: 12
  activation_function: null
  encoder_name: vgg11
  channels_last: false
  scheduler:
    _target_: torch.optim.lr_scheduler.ExponentialLR
    gamma: 0.98
  finetune: true
  pretrained_run_id: 885rnvou
  pretrained_ckpt_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/emulator/885rnvou/checkpoints/epoch=49-step=2950.ckpt
datamodule:
  batch_size: 4
  _target_: emulator.src.datamodules.climate_datamodule.ClimateDataModule
  in_var_ids:
  - BC_sum
  - CO2_sum
  - SO2_sum
  - CH4_sum
  out_var_ids:
  - tas
  - pr
  seq_to_seq: true
  channels_last: false
  eval_batch_size: 4
  train_historical_years: 1850-2010
  test_years: 2015-2100
  train_years: 2015-2100
  val_split: 0.1
  train_scenarios:
  - ssp126
  - ssp370
  - ssp585
  test_scenarios:
  - ssp245
  train_models:
  - NorESM2-LM
  num_ensembles: 1
  num_workers: 0
  pin_memory: false
  load_train_into_mem: true
  load_test_into_mem: true
  verbose: true
  seed: 11
  output_save_dir: /home/mila/v/venkatesh.ramesh/scratch/causal_savedata
  seq_len: 12
  lon: 96
  lat: 144
  num_levels: 1
work_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator
ckpt_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/checkpoints/
log_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/logs/
print_config: true
ignore_warnings: true
test_after_training: true
save_config_to_wandb: true
verbose: true
seed: 22201
name: NorESM2-LM_EC-Earth3_unet_tas+pr_run-01
trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: gpu
  devices: auto
  min_epochs: 1
  max_epochs: 50
  gradient_clip_val: 1.0
  num_sanity_val_steps: 0
callbacks: {}
logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    name: NorESM2-LM_EC-Earth3_unet_tas+pr_run-01UNet_adam_4bs_0.0002lr_1e-06wd_22201seed_11h09m_on_Jun_12_y42j2j79
    tags:
    - finetuning_emulator
    - unet
    - NorESM2-LM_EC-Earth3
    - tas+pr
    - run1
    notes: '...'
    project: emulator
    group: causalpaca
    resume: allow
    reinit: true
    mode: online
    save_dir: /network/scratch/v/venkatesh.ramesh/causalpaca/emulator/
    offline: false
    id: y42j2j79
    log_model: false
    prefix: ''
    job_type: train
experiment_mode: true
local: {}
