name: Create diagram
on:
  workflow_dispatch: {}
  push:
    branches:
      - emulator_structure
jobs:
  get_data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Update diagram
        uses: RolnickLab/causalpaca@emulator_structure
        with:
          excluded_paths: "ignore,.github"
